# Generated by Django 4.0 on 2022-01-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_match_is_finished_news_subtitle_player_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
    ]
