# Generated by Django 4.0 on 2022-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_previous_club_player_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='year_of_join',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
