# Generated by Django 4.0 on 2022-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_player_year_of_join_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year_of_join',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
