# Generated by Django 4.0 on 2022-01-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previous_club',
            name='position',
        ),
        migrations.RemoveField(
            model_name='previous_club',
            name='season',
        ),
        migrations.AddField(
            model_name='player_previous_club',
            name='position',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='player_previous_club',
            name='season',
            field=models.CharField(default='', max_length=20),
        ),
    ]
