# Generated by Django 4.0 on 2022-01-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_player_previous_club_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_previous_club',
            name='group',
        ),
        migrations.AlterField(
            model_name='player_previous_club',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
    ]
