# Generated by Django 4.0 on 2022-01-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_player_previous_club_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
