# Generated by Django 4.0 on 2022-01-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_player_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Grupy'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Mecze'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Aktualności'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Członkowie zespołu'},
        ),
        migrations.AlterModelOptions(
            name='player_previous_club',
            options={'verbose_name_plural': 'Zawodnicy z poprzednimi klubami'},
        ),
        migrations.AlterModelOptions(
            name='previous_club',
            options={'verbose_name_plural': 'Poprzednie kluby'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name_plural': 'Sety'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name_plural': 'Sponsorzy'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Drużyny'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
    ]
