# Generated by Django 4.0 on 2022-01-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comment_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='match',
        ),
        migrations.AddField(
            model_name='set',
            name='match',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.match'),
        ),
    ]
