# Generated by Django 4.0 on 2022-01-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_match_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('matches_played', models.IntegerField(blank=True, null=True)),
                ('matches_won', models.IntegerField(blank=True, null=True)),
                ('matches_lost', models.IntegerField(blank=True, null=True)),
                ('sets_won', models.IntegerField(blank=True, null=True)),
                ('sets_lost', models.IntegerField(blank=True, null=True)),
                ('small_points_won', models.IntegerField(blank=True, null=True)),
                ('small_points_lost', models.IntegerField(blank=True, null=True)),
                ('ratio_sets', models.IntegerField(blank=True, null=True)),
                ('ratio_small_points', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team')),
            ],
            options={
                'verbose_name_plural': 'Tabela',
            },
        ),
    ]
