# Generated by Django 4.0 on 2022-01-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='ratio_sets',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='ratio_small_points',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
