# Generated by Django 4.0 on 2022-01-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_table_ratio_sets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='place',
        ),
    ]
