# Generated by Django 4.0 on 2022-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_table_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='matches_lost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='matches_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='matches_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='ratio_sets',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='ratio_small_points',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='sets_lost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='sets_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='small_points_lost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='small_points_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
