export const PREVIOUS_CLUB_LIST_REQUEST = 'PREVIOUS_CLUB_LIST_REQUEST'
export const PREVIOUS_CLUB_LIST_SUCCESS = 'PREVIOUS_CLUB_LIST_SUCCESS'
export const PREVIOUS_CLUB_LIST_FAIL = 'PREVIOUS_CLUB_LIST_FAIL'
export const PREVIOUS_CLUB_LIST_RESET = 'PREVIOUS_CLUB_LIST_RESET'

export const PREVIOUS_CLUB_DETAILS_REQUEST = 'PREVIOUS_CLUB_DETAILS_REQUEST'
export const PREVIOUS_CLUB_DETAILS_SUCCESS = 'PREVIOUS_CLUB_DETAILS_SUCCESS'
export const PREVIOUS_CLUB_DETAILS_FAIL = 'PREVIOUS_CLUB_DETAILS_FAIL'
export const PREVIOUS_CLUB_DETAILS_RESET = 'PREVIOUS_CLUB_DETAILS_RESET'

export const PREVIOUS_CLUB_DELETE_REQUEST = 'PREVIOUS_CLUB_DELETE_REQUEST'
export const PREVIOUS_CLUB_DELETE_SUCCESS = 'PREVIOUS_CLUB_DELETE_SUCCESS'
export const PREVIOUS_CLUB_DELETE_FAIL = 'PREVIOUS_CLUB_DELETE_FAIL'

export const PREVIOUS_CLUB_CREATE_REQUEST = 'PREVIOUS_CLUB_CREATE_REQUEST'
export const PREVIOUS_CLUB_CREATE_SUCCESS = 'PREVIOUS_CLUB_CREATE_SUCCESS'
export const PREVIOUS_CLUB_CREATE_FAIL = 'PREVIOUS_CLUB_CREATE_FAIL'
export const PREVIOUS_CLUB_CREATE_RESET = 'PREVIOUS_CLUB_CREATE_RESET'

export const PREVIOUS_CLUB_UPDATE_REQUEST = 'PREVIOUS_CLUB_UPDATE_REQUEST'
export const PREVIOUS_CLUB_UPDATE_SUCCESS = 'PREVIOUS_CLUB_UPDATE_SUCCESS'
export const PREVIOUS_CLUB_UPDATE_FAIL = 'PREVIOUS_CLUB_UPDATE_FAIL'
export const PREVIOUS_CLUB_UPDATE_RESET = 'PREVIOUS_CLUB_UPDATE_RESET'