export const SPONSOR_LIST_REQUEST = 'SPONSOR_LIST_REQUEST'
export const SPONSOR_LIST_SUCCESS = 'SPONSOR_LIST_SUCCESS'
export const SPONSOR_LIST_FAIL = 'SPONSOR_LIST_FAIL'
export const SPONSOR_LIST_RESET = 'SPONSOR_LIST_RESET'

export const SPONSOR_DETAILS_REQUEST = 'SPONSOR_DETAILS_REQUEST'
export const SPONSOR_DETAILS_SUCCESS = 'SPONSOR_DETAILS_SUCCESS'
export const SPONSOR_DETAILS_FAIL = 'SPONSOR_DETAILS_FAIL'
export const SPONSOR_DETAILS_RESET = 'SPONSOR_DETAILS_RESET'

export const SPONSOR_DELETE_REQUEST = 'SPONSOR_DELETE_REQUEST'
export const SPONSOR_DELETE_SUCCESS = 'SPONSOR_DELETE_SUCCESS'
export const SPONSOR_DELETE_FAIL = 'SPONSOR_DELETE_FAIL'

export const SPONSOR_CREATE_REQUEST = 'SPONSOR_CREATE_REQUEST'
export const SPONSOR_CREATE_SUCCESS = 'SPONSOR_CREATE_SUCCESS'
export const SPONSOR_CREATE_FAIL = 'SPONSOR_CREATE_FAIL'
export const SPONSOR_CREATE_RESET = 'SPONSOR_CREATE_RESET'

export const SPONSOR_UPDATE_REQUEST = 'SPONSOR_UPDATE_REQUEST'
export const SPONSOR_UPDATE_SUCCESS = 'SPONSOR_UPDATE_SUCCESS'
export const SPONSOR_UPDATE_FAIL = 'SPONSOR_UPDATE_FAIL'
export const SPONSOR_UPDATE_RESET = 'SPONSOR_UPDATE_RESET'