export const TABLE_DETAILS_REQUEST = 'TABLE_DETAILS_REQUEST'
export const TABLE_DETAILS_SUCCESS = 'TABLE_DETAILS_SUCCESS'
export const TABLE_DETAILS_FAIL = 'TABLE_DETAILS_FAIL'
export const TABLE_DETAILS_RESET = 'TABLE_DETAILS_RESET'

export const SHORT_TABLE_DETAILS_REQUEST = 'SHORT_TABLE_DETAILS_REQUEST'
export const SHORT_TABLE_DETAILS_SUCCESS = 'SHORT_TABLE_DETAILS_SUCCESS'
export const SHORT_TABLE_DETAILS_FAIL = 'SHORT_TABLE_DETAILS_FAIL'
export const SHORT_TABLE_DETAILS_RESET = 'SHORT_TABLE_DETAILS_RESET'

